image: alpine/edge
packages:
  - go
sources:
  - https://github.com/Xe/site
tasks:
  - test: |
      export GOPROXY=https://cache.greedo.xeserv.us
      export CGO_ENABLED=0
      cd site
      go test ./...
